### ISSUE TITLE
Repository must have a remote setup to run

### ISSUE THREAD

**Issue by cbzehner** [adamdehaven/change-git-author#2]
Just a quick note for your consideration. I ran `changeauthor.sh` against a local git repository without any remotes set up and it exited early at the [`VALID_REMOTES` check](https://github.com/adamdehaven/change-git-author/blob/master/changeauthor.sh#L396-L403).

I just commented out that section and proceeded as planned, but I want to bring this up in case you haven't encountered this case before.

**Comment by adamdehaven** [comment]
@cbzehner you're on a roll. Thanks again for pointing this out. I have updated the script to allow for remote repositories to be optional. Grab the latest release here: https://github.com/adamdehaven/change-git-author/releases

Let me know if this resolves your use-case. If not, I can re-open this issue. Thanks again :tada:

**Comment by cbzehner** [comment]
Wow, such fast turnaround. Much appreciated! 🙇‍♂️
