### ISSUE TITLE
Change user name only

### ISSUE THREAD

**Issue by olibre** [adamdehaven/change-git-author#4]
I my case I had to change the user name while keeping the same email address.
Thus, I have commented the lines checking `[ "$USER_OLD_EMAIL" == "$USER_NEW_EMAIL" ]` and everything has been successfully renamed. :+1:

I think, in interactive mode, the script should warn and ask the user if the intention is actually to change the user name while keeping the same email address.

A command line argument may also be added for that case where only one email address is requested.

**Comment by adamdehaven** [comment]
@olibre thanks for the suggestion! I have pushed out an updated version that allows users to update the name while passing the same email address for old and new. You are prompted in interactive mode, or pass the `-f` flag if using options. [Grab the latest release here](https://github.com/adamdehaven/change-git-author/releases/latest)
