### ISSUE TITLE
integer expression expected

### ISSUE THREAD

**Issue by chnkd** [adamdehaven/change-git-author#7]
test on 5.1.8 and 3.2.57 of Bash
foo unset
/bin/bash -c '[ "$foo" -eq 0 ]' will cause the error
work if change -eq to =

**Comment by adamdehaven** [comment]
@chsqn so I'm curious as to why you think this change is necessary since all of the variables in the script are explicitly set at the beginning (e.g. they are never unset).

Is the script erroring for you?

**Comment by chnkd** [comment]
https://github.com/adamdehaven/change-git-author/blob/784a52f1894ff83e2d02356cdc84e533749c0b81/changeauthor.sh#L326
https://github.com/adamdehaven/change-git-author/blob/784a52f1894ff83e2d02356cdc84e533749c0b81/changeauthor.sh#L351
UPDATE_NAME only set at two conditions as above.
if USER_OLD_EMAIL != USER_NEW_EMAIL will cause line 355: [: : integer expression expected

**Comment by degaart** [comment]
I printed $UPDATE_NAME just before line 355 and saw UPDATE_NAME was empty. Something's definitely wrong

**Comment by adamdehaven** [comment]
@degaart merged in a fix. Let me know if you have any issues

**Comment by degaart** [comment]
Works for me
